version: '2.2'
services:


   #Remove lines below if you don't plan to use CoTurn in container mode
  coturn:
    image: coturn/coturn:4.5
    container_name: coturn
    restart: always
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 49160-65535:49160-65535/udp
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf
    mem_limit: 600m

